name: Comet Builder

on:
  workflow_dispatch:
  push:
    paths:
      - '**.kt'
      - '**.kts'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.kt'
      - '**.kts'
      - '.github/workflows/*.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 设置 JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          java-package: jdk
          architecture: x64

      - name: Gradle Wrapper 验证
        uses: gradle/wrapper-validation-action@v1

      - uses: burrunan/gradle-cache-action@v1
        name: 检查格式、测试并打包
        with:
          job-id: checker-1
          arguments: ktlintCheck test buildComet --stacktrace
          gradle-version: wrapper

      - uses: actions/upload-artifact@v3
        if: github.event_name != 'pull_request'
        with:
          name: Comet-Bot-full
          path: comet

      - name: 自动发布测试版本
        uses: marvinpinto/action-automatic-releases@v1.2.1
        if: github.event_name != 'pull_request' && contains(github.event.head_commit.message, '[release ready]') == true
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Comet $GITHUB_REF_NAME"
          prerelease: false
          files: |
            comet/*.jar
            comet/modules/*.jar    
