# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Comet Builder

on:
  workflow_dispatch:
  push:
    branches: [ dev, stable, work ]
    paths:
      - '**.kt'
      - '**.kts'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.kt'
      - '**.kts'
      - '.github/workflows/*.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 设置 JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: burrunan/gradle-cache-action@v1
        name: 检查格式、测试并打包
        with:
          job-id: checker
          arguments: ktlintCheck test buildComet
          gradle-version: wrapper

      - uses: actions/upload-artifact@v2
        with:
          name: Comet-Bot-full
          path: comet
